BASE_DIRECTORY: '/share/data_sam2/bigalke/results/registration/neurips_final'
EXPERIMENT_NAME: 'syn_augm'
NUM_WORKERS: 8
USE_AMP: False
DEVICE: 'cuda'
MODEL:
  PPWC_SFPC_BN: False
SOLVER:
  BATCH_SIZE: 4
  NUM_EPOCHS: 1500
  LEARNING_RATE: 0.001
  SCHEDULER: 'multistep'
  LR_LAMBDA: 0.1
  LR_MILESTONES: [1200,1400]
  LOSS_FACTOR: 10.
INPUT:
  SCALE_NORM_FACTOR: 100
AUGMENTATIONS:
  METHOD: 'multiscale_local_global'
  NUM_CONTROL_POINTS_LOCAL: 500
  MAX_CONTROL_SHIFT_LOCAL: 0.03
  KERNEL_STD_LOCAL: 0.15
  GLOBAL_GRID_SPACING: 0.9
  MAX_CONTROL_SHIFT_GLOBAL: 0.25
  KERNEL_STD_GLOBAL: 0.25